# Generated by Django 5.0.7 on 2026-08-24 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cookbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CookbookInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('creator', 'Créateur'), ('editor', 'Éditeur'), ('commentator', 'Commentateur'), ('reader', 'Lecteur')], default='reader', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='cookbooks.cookbook')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CookbookMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'Créateur'), ('editor', 'Éditeur'), ('commentator', 'Commentateur'), ('reader', 'Lecteur')], default='reader', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cookbooks.cookbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbook_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='cookbook',
            index=models.Index(fields=['name'], name='cookbooks_c_name_1ccfa2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cookbookmembership',
            unique_together={('cookbook', 'user')},
        ),
    ]
